import type { APIRoute } from "astro";
import schema from "@errlookup/schema/schema.json";

// The dataset's JSON Schema, generated by the schema package's build
// (scripts/gen-json-schema.ts) and declared as this URL in its $id. /api-docs/
// and llms.txt have linked it since the site launched; nothing ever shipped it,
// so the link was a 404 for as long as it existed. Prerendered: the file is a
// build artifact, and a missing one fails the build instead of serving nothing.
export const GET: APIRoute = () =>
  new Response(JSON.stringify(schema, null, 2), {
    headers: { "content-type": "application/schema+json; charset=utf-8" },
  });
