import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: '{{REPO_NAME}} Errors',
  tagline: 'Error documentation for {{REPO_FULL_NAME}}',
  favicon: 'img/favicon.ico',
  url: 'https://{{SUBDOMAIN}}.errlookup.dev',
  baseUrl: '/',
  organizationName: '{{REPO_OWNER}}',
  projectName: '{{REPO_NAME}}',
  onBrokenLinks: 'warn',
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
          editUrl: undefined,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
        },
      } satisfies Preset.Options,
    ],
  ],
  themeConfig: {
    metadata: [
      {name: 'keywords', content: '{{REPO_NAME}}, errors, documentation, troubleshooting'},
      {name: 'description', content: 'Error documentation and solutions for {{REPO_FULL_NAME}}'},
    ],
    navbar: {
      title: '{{REPO_NAME}} Errors',
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'errorsSidebar',
          position: 'left',
          label: 'Errors',
        },
        {
          href: 'https://github.com/{{REPO_FULL_NAME}}',
          label: 'GitHub',
          position: 'right',
        },
        {
          href: 'https://errlookup.dev',
          label: 'ErrLookup',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Documentation',
          items: [
            {
              label: 'All Errors',
              to: '/',
            },
          ],
        },
        {
          title: 'Repository',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/{{REPO_FULL_NAME}}',
            },
            {
              label: 'Issues',
              href: 'https://github.com/{{REPO_FULL_NAME}}/issues',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'ErrLookup',
              href: 'https://errlookup.dev',
            },
          ],
        },
      ],
      copyright: `Generated by ErrLookup. Data sourced from {{REPO_FULL_NAME}}.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'json', 'typescript', 'python', 'go', 'rust', 'java'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
