import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  errorsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Errors',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'errors'}],
    },
  ],
};

export default sidebars;
